apiVersion: v1
entries:
  worker:
  - apiVersion: v2
    appVersion: 0.50.33
    created: "2023-11-27T13:55:09.525969+01:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Helm chart to deploy airbyte-worker
    digest: 3ae439086d17bef47d4a5d29a49fc3011e07b87d7331dd0b10053e11c74d30c4
    name: worker
    type: application
    urls:
    - https://core-ops-charts.storage.googleapis.com/airbyte-worker/worker-0.49.6.tgz
    version: 0.49.6
generated: "2023-11-27T13:55:09.524725+01:00"
