apiVersion: v1
entries:
  airbyte:
  - apiVersion: v2
    appVersion: 0.50.33
    created: "2023-11-24T21:24:53.314337+01:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    - condition: airbyte-bootloader.enabled
      name: airbyte-bootloader
      repository: https://airbytehq.github.io/helm-charts/
      version: 0.50.2
    - condition: temporal.enabled
      name: temporal
      repository: https://airbytehq.github.io/helm-charts/
      version: 0.50.2
    - condition: webapp.enabled
      name: webapp
      repository: https://airbytehq.github.io/helm-charts/
      version: 0.50.2
    - condition: server.enabled
      name: server
      repository: https://airbytehq.github.io/helm-charts/
      version: 0.50.2
    - condition: airbyte-api-server.enabled
      name: airbyte-api-server
      repository: https://airbytehq.github.io/helm-charts/
      version: 0.50.2
    - condition: worker.enabled
      name: worker
      repository: https://core-ops-charts.storage.googleapis.com/airbyte-worker/
      version: 0.50.2
    - condition: pod-sweeper.enabled
      name: pod-sweeper
      repository: https://airbytehq.github.io/helm-charts/
      version: 0.50.2
    - condition: metrics.enabled
      name: metrics
      repository: https://airbytehq.github.io/helm-charts/
      version: 0.50.2
    - condition: cron.enabled
      name: cron
      repository: https://airbytehq.github.io/helm-charts/
      version: 0.50.2
    - condition: connector-builder-server.enabled
      name: connector-builder-server
      repository: https://airbytehq.github.io/helm-charts/
      version: 0.50.2
    - condition: keycloak.enabled
      name: keycloak
      repository: https://airbytehq.github.io/helm-charts/
      version: 0.50.2
    - condition: keycloak-setup.enabled
      name: keycloak-setup
      repository: https://airbytehq.github.io/helm-charts/
      version: 0.50.2
    description: Helm chart to deploy airbyte
    digest: d0c81810a8e5ba1fb50b9237f7ee61a5c5d5f949ee73a9624e40c862a4cf7e84
    name: airbyte
    type: application
    urls:
    - https://core-ops-charts.storage.googleapis.com/airbyte/airbyte-0.50.2.tgz
    version: 0.50.2
generated: "2023-11-24T21:24:53.292504+01:00"
